module DiffHelper
  protected
  # calls the calculation of the diff and returns the output generated by the 
  # optional third argument, which defaults to the plug-ins's provided one, which
  # generates table-rows
  def diff(old, new, output = Output::SimpleHtmlDiff)
    RailsDiff.diff(old, new, output)
  end
end
